### ISSUE TITLE
Is this a bug in Resizer.forward()? My understanding is to return out here

### ISSUE THREAD

**Issue by ado-ml** [KushajveerSingh/resize_network_cv#1]
def forward(self, x):
        residual = self.interpolate(x)

        out = self.module1(x)
        out_residual = self.interpolate(out)

        out = self.resblocks(out_residual)
        out = self.module3(out)
        out = out + out_residual

        out = self.module4(out)

        out = out + residual

        return x

**Comment by bilzard** [comment]
I think it's bug.

**Comment by bilzard** [comment]
@KushajveerSingh I made PR, please review.

**Comment by KushajveerSingh** [comment]
Thanks for the help.
